defaults: &defaults
  app_name: OverlGames
  app_host: overlgames.com
  smtp:
    sender: support@overlgames.com
    address: smtp.mandrillapp.com
    port: 587
    authentication: plain
    username: renkaiswpu@gmail.com
    password: Sli2ZTZSxGS6g6rKp9lwkw

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
